Repository ClusterLabs/pacemaker, pull requests merged in 2025-02, with the labels that each got.

#3816 Prepare for the systemd+dbus PR
  daemons/execd/execd_commands.c
  lib/services/dbus.c
  lib/services/systemd.c
Labels: review: in progress

#3810 Fix memory issues with pcmk__schedule_actions()
  daemons/fenced/fenced_scheduler.c
  daemons/schedulerd/schedulerd_messages.c
  include/pacemaker.h
  include/pcmki/pcmki_scheduler.h
  include/pcmki/pcmki_simulate.h
  lib/pacemaker/pcmk_scheduler.c
  lib/pacemaker/pcmk_simulate.c
  lib/pacemaker/pcmk_verify.c
  lib/pengine/status.c
  tools/crm_resource_runtime.c
  tools/crm_simulate.c
Labels: review: in progress

#3828 [2.1] Fix: build: Fix default pacemaker-remoted path on Fedora >= 42
  configure.ac
Labels: branch: 2.1

#3827 [3.0] Fix: build: Fix default pacemaker-remoted path on Fedora >= 42
  configure.ac
Labels: branch: 3.0
