Repository ClusterLabs/pacemaker, pull requests merged in 2025-04, with the labels that each got.

#3861 Backport IPC prep to 2.1
  include/crm/common/ipc.h
  lib/common/ipc_client.c
Labels: branch: 2.1

#3856 Change fencing behavior for Pacemaker Remote nodes in certain circumstances
  cts/cli/regression.daemons.exp
  cts/cli/regression.tools.exp
  include/crm/common/options_internal.h
  include/crm/common/scheduler.h
  lib/common/options.c
  lib/pengine/unpack.c
  lib/pengine/utils.c
Labels: branch: 2.1

#3860 Fix: pacemaker-attrd: prevent segfault if a peer leaves when its name is unknown yet
  daemons/attrd/attrd_corosync.c
  daemons/attrd/attrd_messages.c
  daemons/attrd/pacemaker-attrd.c
  daemons/attrd/pacemaker-attrd.h
  lib/cluster/cluster.c
Labels: branch: 2.1

#3867 Refactor: libcrmcommon: move the new struct member to the end for backward compatibility
  include/crm/common/scheduler.h
Labels: branch: 2.1

#3863 Some fencer device registration refactors
  cts/cts-fencing.in
  cts/support/fence_dummy.in
  daemons/fenced/fenced_cib.c
  daemons/fenced/fenced_commands.c
  daemons/fenced/fenced_scheduler.c
  daemons/fenced/pacemaker-fenced.c
  daemons/fenced/pacemaker-fenced.h
  doc/sphinx/Pacemaker_Explained/fencing.rst
  include/crm/fencing/internal.h
  lib/fencing/st_actions.c
  lib/fencing/st_client.c
  lib/fencing/st_rhcs.c
Labels: review: in progress

#3866 More fencer refactors (mostly related to flags)
  daemons/controld/controld_fencing.c
  daemons/execd/execd_commands.c
  daemons/execd/pacemaker-execd.c
  daemons/fenced/cts-fence-helper.c
  daemons/fenced/fenced_cib.c
  daemons/fenced/fenced_commands.c
  daemons/fenced/fenced_history.c
  daemons/fenced/fenced_remote.c
  daemons/fenced/fenced_scheduler.c
  daemons/fenced/pacemaker-fenced.c
  daemons/fenced/pacemaker-fenced.h
  include/crm/fencing/internal.h
  include/crm/stonith-ng.h
  include/pacemaker.h
  include/pcmki/pcmki_fence.h
  lib/fencing/st_actions.c
  lib/fencing/st_client.c
  lib/fencing/st_lha.c
  lib/fencing/st_output.c
  lib/fencing/st_rhcs.c
  lib/lrmd/lrmd_client.c
  lib/pacemaker/pcmk_fence.c
  lib/pacemaker/pcmk_setup.c
  lib/pacemaker/pcmk_status.c
  tools/crm_mon.c
  tools/crm_resource.c
  tools/stonith_admin.c
Labels: review: in progress

#3853 XML refactors/deprecations: xml_accept_changes() to xml_calculate_significant_changes()
  daemons/based/based_callbacks.c
  include/crm/common/acl_internal.h
  include/crm/common/xml.h
  include/crm/common/xml_compat.h
  include/crm/common/xml_internal.h
  lib/cib/cib_utils.c
  lib/common/acl.c
  lib/common/crmcommon_private.h
  lib/common/patchset.c
  lib/common/tests/patchset/pcmk__cib_element_in_patchset_test.c
  lib/common/tests/xml/pcmk__xml_new_doc_test.c
  lib/common/tests/xml_comment/pcmk__xc_create_test.c
  lib/common/tests/xml_element/pcmk__xe_sort_attrs_test.c
  lib/common/xml.c
  lib/common/xml_comment.c
  lib/common/xml_element.c
  tools/crm_diff.c
  tools/crm_shadow.c
Labels: review: in progress

#3873 [3.0] Drop deprecated xmlSetBufferAllocationScheme() call (fix builds on debian-experimental)
  include/crm/common/xml_internal.h
  lib/common/logging.c
  lib/common/tests/schemas/pcmk__build_schema_xml_node_test.c
  lib/common/tests/schemas/pcmk__cmp_schemas_by_name_test.c
  lib/common/tests/schemas/pcmk__get_schema_test.c
  lib/common/tests/schemas/pcmk__schema_files_later_than_test.c
  lib/common/tests/schemas/pcmk__schema_init_test.c
  lib/common/tests/xml/Makefile.am
  lib/common/tests/xml/pcmk__xml_init_test.c
  lib/common/unittest.c
  lib/common/utils.c
  lib/common/xml.c
  lib/pengine/tests/native/native_find_rsc_test.c
  lib/pengine/tests/native/pe_base_name_eq_test.c
Labels: branch: 3.0
