Repository ClusterLabs/pacemaker, pull requests merged in 2025-07, with the labels that each got.

#3898 Start addressing unchecked snprintf() calls
  daemons/based/based_callbacks.c
  daemons/execd/cts-exec-helper.c
  daemons/execd/remoted_tls.c
  daemons/fenced/cts-fence-helper.c
  daemons/fenced/fenced_commands.c
  daemons/pacemakerd/pcmkd_corosync.c
  doc/sphinx/Pacemaker_Explained/alerts.rst
  include/crm/common/internal.h
  include/crm/common/iso8601_internal.h
  lib/common/attrs.c
  lib/common/iso8601.c
  lib/common/logging.c
  lib/common/mock.c
  lib/common/options.c
  lib/common/output_log.c
  lib/common/pid.c
  lib/common/procfs.c
  lib/common/scores.c
  lib/common/tests/iso8601/pcmk__time_format_hr_test.c
  lib/common/tests/options/pcmk__env_option_test.c
  lib/common/tests/options/pcmk__set_env_option_test.c
  lib/common/tests/procfs/pcmk__procfs_has_pids_false_test.c
  lib/common/tests/procfs/pcmk__procfs_has_pids_true_test.c
  lib/common/tests/procfs/pcmk__procfs_pid2path_test.c
  lib/common/tests/strings/pcmk__scan_double_test.c
  lib/common/xml_element.c
  lib/fencing/st_actions.c
  lib/lrmd/lrmd_alerts.c
  lib/pacemaker/pcmk_output.c
  lib/pengine/bundle.c
  lib/pengine/native.c
  lib/services/services_linux.c
  lib/services/services_lsb.c
Labels: review: in progress

#3911 Update documentation
  doc/sphinx/Clusters_from_Scratch/active-active.rst
  doc/sphinx/Clusters_from_Scratch/ap-configuration.rst
  doc/sphinx/Clusters_from_Scratch/cluster-setup.rst
  doc/sphinx/Clusters_from_Scratch/index.rst
  doc/sphinx/Clusters_from_Scratch/installation.rst
  doc/sphinx/Clusters_from_Scratch/shared-storage.rst
  doc/sphinx/Clusters_from_Scratch/verification.rst
  doc/sphinx/Pacemaker_Administration/agents.rst
  doc/sphinx/Pacemaker_Administration/alerts.rst
  doc/sphinx/Pacemaker_Administration/index.rst
  doc/sphinx/Pacemaker_Administration/intro.rst
  doc/sphinx/Pacemaker_Administration/moving.rst
  doc/sphinx/Pacemaker_Administration/options.rst
  doc/sphinx/Pacemaker_Administration/pcs-crmsh.rst
  doc/sphinx/Pacemaker_Administration/tools.rst
  doc/sphinx/Pacemaker_Administration/troubleshooting.rst
  doc/sphinx/Pacemaker_Administration/upgrading.rst
  doc/sphinx/Pacemaker_Development/c.rst
  doc/sphinx/Pacemaker_Development/components.rst
  doc/sphinx/Pacemaker_Development/faq.rst
  doc/sphinx/Pacemaker_Development/general.rst
  doc/sphinx/Pacemaker_Development/index.rst
  doc/sphinx/Pacemaker_Explained/acls.rst
  doc/sphinx/Pacemaker_Explained/alerts.rst
  doc/sphinx/Pacemaker_Explained/ap-samples.rst
  doc/sphinx/Pacemaker_Explained/cluster-options.rst
  doc/sphinx/Pacemaker_Explained/collective.rst
  doc/sphinx/Pacemaker_Explained/constraints.rst
  doc/sphinx/Pacemaker_Explained/fencing.rst
  doc/sphinx/Pacemaker_Explained/index.rst
  doc/sphinx/Pacemaker_Explained/intro.rst
  doc/sphinx/Pacemaker_Explained/local-options.rst
  doc/sphinx/Pacemaker_Explained/multi-site-clusters.rst
  doc/sphinx/Pacemaker_Explained/nodes.rst
  doc/sphinx/Pacemaker_Explained/operations.rst
  doc/sphinx/Pacemaker_Explained/resources.rst
  doc/sphinx/Pacemaker_Explained/reusing-configuration.rst
  doc/sphinx/Pacemaker_Explained/rules.rst
  doc/sphinx/Pacemaker_Explained/status.rst
Labels: review: in progress

#3918 Update documentation
  doc/sphinx/Clusters_from_Scratch/active-active.rst
  doc/sphinx/Clusters_from_Scratch/ap-configuration.rst
  doc/sphinx/Clusters_from_Scratch/cluster-setup.rst
  doc/sphinx/Clusters_from_Scratch/index.rst
  doc/sphinx/Clusters_from_Scratch/installation.rst
  doc/sphinx/Clusters_from_Scratch/shared-storage.rst
  doc/sphinx/Clusters_from_Scratch/verification.rst
  doc/sphinx/Pacemaker_Administration/agents.rst
  doc/sphinx/Pacemaker_Administration/alerts.rst
  doc/sphinx/Pacemaker_Administration/index.rst
  doc/sphinx/Pacemaker_Administration/intro.rst
  doc/sphinx/Pacemaker_Administration/moving.rst
  doc/sphinx/Pacemaker_Administration/options.rst
  doc/sphinx/Pacemaker_Administration/pcs-crmsh.rst
  doc/sphinx/Pacemaker_Administration/tools.rst
  doc/sphinx/Pacemaker_Administration/troubleshooting.rst
  doc/sphinx/Pacemaker_Administration/upgrading.rst
  doc/sphinx/Pacemaker_Development/c.rst
  doc/sphinx/Pacemaker_Development/components.rst
  doc/sphinx/Pacemaker_Development/faq.rst
  doc/sphinx/Pacemaker_Development/general.rst
  doc/sphinx/Pacemaker_Development/index.rst
  doc/sphinx/Pacemaker_Explained/acls.rst
  doc/sphinx/Pacemaker_Explained/alerts.rst
  doc/sphinx/Pacemaker_Explained/ap-samples.rst
  doc/sphinx/Pacemaker_Explained/cluster-options.rst
  doc/sphinx/Pacemaker_Explained/collective.rst
  doc/sphinx/Pacemaker_Explained/constraints.rst
  doc/sphinx/Pacemaker_Explained/fencing.rst
  doc/sphinx/Pacemaker_Explained/index.rst
  doc/sphinx/Pacemaker_Explained/intro.rst
  doc/sphinx/Pacemaker_Explained/local-options.rst
  doc/sphinx/Pacemaker_Explained/multi-site-clusters.rst
  doc/sphinx/Pacemaker_Explained/nodes.rst
  doc/sphinx/Pacemaker_Explained/operations.rst
  doc/sphinx/Pacemaker_Explained/resources.rst
  doc/sphinx/Pacemaker_Explained/reusing-configuration.rst
  doc/sphinx/Pacemaker_Explained/rules.rst
  doc/sphinx/Pacemaker_Explained/status.rst
Labels: branch: 3.0

#3917 Doc: ChangeLog: update for 2.1.10 release
  ChangeLog
Labels: branch: 2.1

#3919 Doc: ChangeLog: update for 3.0.1-rc2 release
  ChangeLog.md
Labels: branch: 3.0

#3915 Convert execd to use pcmk__request_t
  daemons/attrd/attrd_messages.c
  daemons/execd/Makefile.am
  daemons/execd/execd_alerts.c
  daemons/execd/execd_commands.c
  daemons/execd/execd_messages.c
  daemons/execd/pacemaker-execd.c
  daemons/execd/pacemaker-execd.h
  daemons/execd/remoted_tls.c
  daemons/fenced/fenced_commands.c
  daemons/pacemakerd/pcmkd_messages.c
  daemons/schedulerd/schedulerd_messages.c
Labels: review: in progress
